[env:esp32dev]
platform = espressif32
board = nodemcu-32s

framework = arduino
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.partitions = huge_app.csv

lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.4
    olikraus/U8g2@^2.35.21
    nRF24/RF24@^1.4.10
    ESP32 BLE Arduino
    SPI
    Wire
